LinQ = "https://www.lingq.com/?referral=authenticgermanlearning&utm_source=affiliate&utm_medium=referral-link&utm_campaign=authenticgermanlearning"
Patreon = "https://patreon.com/invite/gvmymz"
"Canon LEGRIA/VIXIA mini X" = "http://geni.us/CanonCam"
Huel = "https://huel.mention-me.com/m/ol/at8bq-marco-rosler"
ConvertKit = "http://mbsy.co/convertkit/31725296"
Gumroad = "https://gumroad.com/invite/markrosemaker"

[bunq]
link = "https://bunq.com/invite/MarkRosemaker"
description = "Bunq is a banking app that allows you to make multiple free bank accounts with a tap on your phone. I use it to sort my money into \"buckets\" and to have a better overview."
weight = 1.0
what = "mobile banking app"
benefit = "If you sign up with this link, we'll both get 10€ the first time you use your bunq card."

[Weekdone]
link = "https://weekdone.com/&utm_campaign=referral-444593-124755"
what = "OKR (objectives and key results) management tool"

[Siteground]
link = "https://www.siteground.com/recommended?referrer_id=7686347"
what = "hosting"

[MeetEdgar]
link = "https://meetedgar.com/?tap_a=24217-bf650d&tap_s=200619-50f96a"
what = "automatic post publishing"

[Siteguarding]
link = "https://www.siteguarding.com/en/affiliate?partner_id=12489"
what = "website protection and cleaning"

[Planoly]
link = "https://www.planoly.com/referral/authenticgermanlearning"
what = "schedule Instagram pictures"

["WP Rocket"]
link = "https://shareasale.com/r.cfm?b=1075949&u=1866713&m=74778&urllink=wp%2Drocket%2Eme&afftrack="
what = "WordPress website acceleration"

[Xolo]
site = "https://www.xolo.io/"
note = "Tell them \"Marco Rösler\" sent you to get a free first month."
description = "Xolo helps you set up a company and e-residency in Estonia, gives tax consultancy, bookkeeping, and more for a flat fee."