# Discussion
  twitter = "MarkRosemaker"
  facebook = "MarkRosemaker"
  #reddit = "MarkRosemaker"
# Business
  #linkedin = "MarkRosemaker"
  #xing = "Mark_Rosemaker"
# Shop
  #amazon = "" # (geni.us) link to shop
# Blog
  #medium = "MarkRosemaker"
  goodreads = "MarkRosemaker"
  #tumblr = "MarkRosemaker"
# Videos
  #youtube = "channel/UCwwRAmpWj_G5zobN0yAnqVQ"
  #vimeo = "MarkRosemaker"
# Images
  instagram = "MarkRosemaker"
  #pinterest = "MarkRosemaker"
  #pixabay = "MarkRosemaker"
  #flickr = "MarkRosemaker"
  #"500px" = "MarkRosemaker"
  #deviantart = "MarkRosemaker"
# Programming
  github = "MarkRosemaker"
  #codepen = "MarkRosemaker"
# music
  #spotify = "MarkRosemaker" #TODO
#contact
  facebook-messenger = "MarkRosemaker"
  #whatsapp = "+49 30 23327134"
# Gaming
  #steam = "MarkRosemaker" #  "https://steamcommunity.com/id/markrosemaker/"
# Knowledge
  #wikipedia = "MarkRosemaker"